name: Go

on:
  push:
    branches: ["main"]
    tags: ["v*"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            runner: ubuntu-latest
            binary: lightcode-linux-amd64

          - goos: linux
            goarch: arm64
            runner: ubuntu-24.04-arm
            binary: lightcode-linux-arm64

          # can't find a runner immediately...duh(idk how long to wait)
          - goos: darwin
            goarch: amd64
            runner: macos-15-intel
            binary: lightcode-darwin-amd64

          - goos: darwin
            goarch: arm64
            runner: macos-latest
            binary: lightcode-darwin-arm64

          - goos: windows
            goarch: amd64
            runner: windows-latest
            binary: lightcode-windows-amd64.exe
          
          # can't find a runner immediately (idk how long to wait) 
          - goos: windows
            goarch: arm64
            runner: windows-11-arm
            binary: lightcode-windows-amd64.exe

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Create dist directory
        run: mkdir -p dist

      - name: Install Linux dependencies
        if: matrix.goos == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libx11-dev \
          libxkbcommon-dev \
          xorg-dev

      # - name: Install upx for macos and linux 
      #   if: matrix.goos != 'windows'
      #   run: |
      #     if [[ "$RUNNER_OS" == "Linux" ]]; then
      #       sudo apt-get update
      #       sudo apt-get install -y upx-ucl || sudo apt-get install -y upx
      #     elif [[ "$RUNNER_OS" == "macOS" ]]; then
      #       brew install upx
      #     fi

      # - name: Install upx for windows
      #   if: matrix.goos == 'windows'
      #   shell: powershell
      #   run: |
      #     choco install upx -y

      - name: Build
        run: go build -trimpath -ldflags="-s -w" -o dist/${{ matrix.binary }} ./cmd/lightcode
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
      # - name: Compress binary
      #   run: upx --best --lzma dist/${{ matrix.binary }}

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.binary }}
          path: dist/${{ matrix.binary }}

  release:
    needs: build

    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist

      - name: Flatten files
        run: |
          mkdir -p release
          find dist -type f -exec mv {} release/ \;

      - name: Generate checksums
        working-directory: release
        run: |
          sha256sum * > checksums.txt
          cat checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*